# Generated by Django 4.0.10 on 2025-03-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
    ]
